### ISSUE TITLE
请问一下，这个是markdown哪个语法撒

### ISSUE THREAD

**Issue by spaco** [ike-c/hexo-theme-inside#103]
![image](https://user-images.githubusercontent.com/24441899/60513353-a335f680-9d09-11e9-9a27-08df4ffaf4c7.png)

**Comment by ike-c** [comment]
所有你查不到的表现形式，基本都是我自定义的东西，和主题无关

**Comment by ike-c** [comment]
这是写了个 hexo tag，把 yaml 渲染成类似 `<detail>` 标签那样的形式

```yml
{% details theme-inside/docs/basic %}
appearance:
  accent_color: appearance
  background: appearance
  content_width: appearance
  font:
    base: appearance
    logo: appearance
    menu: appearance
    label: appearance
    heading: appearance
    code: appearance
profile:
  avatar: profile
  email: profile
  bio: profile
menu:
sns:
footer:
  copyright: footer
  powered: footer
  theme: footer
  custom: footer
{% enddetails %}
```
