### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by toperc** [ike-c/hexo-theme-inside#81]
1. 发现图片放大缩小多次偶尔会卡住。
2. 新版2.2.0主题配置中那个字体url的css内部规则不了解，下边设置项的字体配置都是来源于这个css吗？这里无从下手。

**Comment by elmorec** [comment]
1. 这问题我知道，下个版本修复。
2. 无从下手是因为你不了解 CSS，或者说不了解网络字体，有效字体来源于系统字体+ URL 引入的字体，至于这个 CSS 文件里如何写，`@font-face` 了解下。

贴一个 NexT 主题选用的字体给你试试：

```yml
appearance:
  font: 
    url: https://fonts.googleapis.com/css?family=Monda:400,700|Rosario:400,700|PT%20Mono:400,700
    base: "Monda, 'PingFang SC', 'Microsoft YaHei'"
    logo: Rosario
    menu: impact
    label:
    code: "'PT Mono', consolas"
```

注：**impact 是系统字库，非 NexT 主题选用，也不依赖 URL 引入的字体**，这里只是举个例子；另外，你可以直接访问这个 URL 看看里面是如何写的。
