### ISSUE TITLE
About Plugins

### ISSUE THREAD

**Issue by shuntan** [ike-c/hexo-theme-inside#98]
>https://blog.oniuo.com/theme-inside/docs/misc#plugins

首先要说一下，主题的插件扩展功能真的挺好用的。但是要修改layout/index.ejs还是让人有点小不爽。

Tips：能否在template的基础上再扩个script和css字段？

like this：
```
plugins:
  - position: comments
    template: |
      <div id="gitment"></div>
      <script>
      ....
      </script>
     css: //imsun.github.io/gitment/style/default.css
     script: //imsun.github.io/gitment/dist/gitment.browser.js
     // 最好支持数组
```

我之前尝试在template里引入js文件，但似乎是渲染之后加载的，没有生效...
```
    template: |
      <script>
        const script = document.createElement('script');
        script.src='xx.js';
        document.head.appendChild(script);
        ... // 我的逻辑
      </script>
```

**Comment by ike-c** [comment]
不错 👍。

**Comment by ike-c** [comment]
支持了，一劳永逸，目前没发现 bug，不知是否有遗漏，欢迎反馈~

```yaml
plugins:
  # 动态插入可执行的代码片段
  - position: # `sidebar` | `post` | `page` | `comments`, 支持数组
    template:

  # 全局加载脚本/样式
  - xxx.css
  - xxx.js

  # 更灵活的用法

  # <script src="//sample.com/api.php?format=jsonp" id="sample-api" defer></script>
  - tag: script # html 标签, `script` | `style` | `link`
    # Any possible attributes
    src: //sample.com/api.php?format=jsonp
    id: sample-api
    defer: true

  # <link rel="stylesheet" href="xxx.css" disable>
  - tag: link
    href: xxx.css
    disable: true

  # 内联脚本需指定 code
  # <script type="text/x-mathjax-config">MathJax.Hub.Config({...})</script>
  - tag: script
    type: text/x-mathjax-config
    code: |
        MathJax.Hub.Config({
          showProcessingMessages: false,
          messageStyle: 'none',
          tex2jax: { inlineMath: [['s;,'s;], ['\\(','\\)']] }
        })

  # 内联样式
  # <style>.mycss{...}</style>
  - tag: style
    code: |
        .mycss {
          color: rebeccapurple;
        }
```

这里有更详细的例子 https://blog.oniuo.com/theme-inside/docs/misc#plugins 。
